apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    karpenter.sh/nodepool: emr
    app: emr
  containers:
  - name: spark-kubernetes-driver
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /data1
  initContainers:  
  - name: volume-permission
    image: public.ecr.aws/docker/library/busybox:stable-musl
    command: ['sh', '-c', 'mkdir /data1 || true; chown -R 999:1000 /data*'] # grant volume access to hadoop user  
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /data1
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: /local1 

