kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $KYUUBI_SA-rolebinding
  namespace: $EMR_NAMESPACE
subjects:
- kind: ServiceAccount
  name: $KYUUBI_SA
  namespace: $EMR_NAMESPACE
roleRef:
  kind: Role
  name: emr-containers-role-spark-driver
  apiGroup: rbac.authorization.k8s.io