apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: $CLUSTER_NAME
  region: $AWS_REGION
  version: "$EKS_VERSION"
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true   
    roleName: $CLUSTER_NAME-$AWS_REGION-ebs-csidriver-role  
  # - metadata:
  #     name: cross-ns-kyuubi
  #     namespace: $KYUUBI_NAMESPACE
  #     labels: {aws-usage: "app"}
  #   attachPolicyARNs:
  #   - arn:aws:iam::${AWS_ACCOUNT_ID}:policy/JOB_EXECUTION_POLICY_NAME
  #   roleName: $EKSCLUSTER_NAME-$AWS_REGION-kyuubi-role